/* Generated by re2c 0.16 on Sat Jul 15 05:38:49 2017 */
#line 1 "php_serializer.re"
#include<ruby.h>
#include<php_serializer.h>

#define YYFILL(n) do { } while (0)
#define YYCTYPE unsigned char
#define YYCURSOR cursor
#define YYLIMIT limit
#define YYMARKER marker

void
Init_php_serializer ()
{
  VALUE php_serializer_module = rb_define_module ("PhpSerializer");
  rb_define_singleton_method (php_serializer_module, "serialize", serialize,
                              1);
  rb_define_singleton_method (php_serializer_module, "unserialize",
                              unserialize, 1);
}

static inline void
serialize_long (php_str * buf, long val)
{
  php_str_appendl (buf, "i:", 2);
  php_str_append_long (buf, val);
  php_str_appendc (buf, ';');
}

static inline void
serialize_float (php_str * buf, VALUE flt)
{
  VALUE str = Qnil;
  str = rb_funcall (flt, rb_intern ("to_s"), 0);
  php_str_appendl (buf, "d:", 2);
  php_str_appendl (buf, RSTRING_PTR (str), RSTRING_LEN (str));
  php_str_appendc (buf, ';');
}

static inline void
serialize_string (php_str * buf, char *str, int len)
{
  php_str_appendl (buf, "s:", 2);
  php_str_append_long (buf, len);
  php_str_appendl (buf, ":\"", 2);
  php_str_appendl (buf, str, len);
  php_str_appendl (buf, "\";", 2);
}

static inline void
serialize_array (php_str * buf, VALUE arr)
{
  long arr_len = RARRAY_LEN (arr);
  php_str_appendl (buf, "a:", 2);
  php_str_append_long (buf, arr_len);
  php_str_appendl (buf, ":{", 2);
  for (long i = 0; i < arr_len; i++)
    {
      php_str_appendl (buf, "i:", 2);
      php_str_append_long (buf, i);
      php_str_appendl (buf, ";", 1);
      serialize_intern (buf, RARRAY_AREF (arr, i));
    }
  php_str_appendl (buf, "}", 1);
}

static inline int
rb_hash_each (VALUE key, VALUE val, VALUE rbuf)
{
  php_str buf = { 0 };
  serialize_intern (&buf, key);
  serialize_intern (&buf, val);
  rb_str_cat (rbuf, buf.c, buf.len);
  php_str_free (&buf);
  return ST_CONTINUE;
}

static inline void
serialize_hash (php_str * buf, VALUE hash)
{
  long hash_size;
  VALUE rbuf = rb_str_new_cstr ("");
  hash_size = RHASH_SIZE (hash);
  php_str_appendl (buf, "a:", 2);
  php_str_append_long (buf, hash_size);
  php_str_appendl (buf, ":{", 2);
  rb_hash_foreach (hash, rb_hash_each, rbuf);
  php_str_appendl (buf, StringValueCStr (rbuf), RSTRING_LEN (rbuf));
  php_str_appendl (buf, "}", 1);
}

static inline void
serialize_symbol (php_str * buf, VALUE sym)
{
  VALUE str = rb_sym_to_s (sym);
  serialize_string (buf, RSTRING_PTR (str), RSTRING_LEN (str));
}

static void
serialize_intern (php_str * buf, VALUE in_data)
{
  switch (TYPE (in_data))
    {
    case T_NIL:
      php_str_appendl (buf, "N;", 2);
      break;
    case T_TRUE:
      php_str_appendl (buf, "b:1;", 4);
      break;
    case T_FALSE:
      php_str_appendl (buf, "b:0;", 4);
      break;
    case T_FIXNUM:
      serialize_long (buf, FIX2LONG (in_data));
      break;
    case T_BIGNUM:
      serialize_long (buf, NUM2LONG (in_data));
      break;
    case T_STRING:
      serialize_string (buf, RSTRING_PTR (in_data), RSTRING_LEN (in_data));
      break;
    case T_SYMBOL:
      serialize_symbol (buf, in_data);
      break;
    case T_ARRAY:
      serialize_array (buf, in_data);
      break;
    case T_HASH:
      serialize_hash (buf, in_data);
      break;
    case T_FLOAT:
      serialize_float (buf, in_data);
      break;
    default:
      /* raise exception */
      rb_raise (rb_eTypeError, "%s is not valid value",
                RSTRING_PTR (rb_any_to_s (rb_obj_class (in_data))));
      break;
    }
}

static inline long
parse_iv (unsigned char *p)
{
  char cursor;
  long result = 0;
  int neg = 0;

  switch (*p)
    {
    case '-':
      neg++;
      /* fall-through */
    case '+':
      p++;
    }

  while (1)
    {
      cursor = (char) *p;
      if (cursor >= '0' && cursor <= '9')
        {
          result =
            result * 10 + (unsigned int) (cursor - (unsigned char) '0');
        }
      else
        {
          break;
        }
      p++;
    }
  if (neg)
    return -result;
  return result;
}

static inline unsigned int
parse_uiv (unsigned char *p)
{
  unsigned char cursor;
  unsigned int result = 0;

  if (*p == '+')
    {
      p++;
    }

  while (1)
    {
      cursor = *p;
      if (cursor >= '0' && cursor <= '9')
        {
          result =
            result * 10 + (unsigned int) (cursor - (unsigned char) '0');
        }
      else
        {
          break;
        }
      p++;
    }
  return result;
}

static inline void
raise_incomplete_serialization ()
{
  rb_raise (rb_eTypeError, "Incomplete Serialization.");
}


#line 201 "php_serializer.re"

static VALUE
unserialize_intern (unsigned char **p, unsigned char *max)
{
  VALUE rval = Qnil;
  unsigned char *cursor, *limit, *marker, *start;

  limit = max;
  cursor = *p;

  if (YYCURSOR >= YYLIMIT)
    {
      return 0;
    }

  start = cursor;


#line 215 "php_serializer.c"
  {
    YYCTYPE yych;
    if ((YYLIMIT - YYCURSOR) < 7)
      YYFILL (7);
    yych = *YYCURSOR;
    switch (yych)
      {
      case 'N':
        goto yy4;
      case 'a':
        goto yy5;
      case 'b':
        goto yy6;
      case 'd':
        goto yy7;
      case 'i':
        goto yy8;
      case 's':
        goto yy9;
      default:
        goto yy2;
      }
  yy2:
    ++YYCURSOR;
  yy3:
#line 319 "php_serializer.re"
    {
      rb_raise (rb_eTypeError, "Invalid Serialization.");
    }
#line 234 "php_serializer.c"
  yy4:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case ';':
        goto yy10;
      default:
        goto yy3;
      }
  yy5:
    yych = *(YYMARKER = ++YYCURSOR);
    switch (yych)
      {
      case ':':
        goto yy12;
      default:
        goto yy3;
      }
  yy6:
    yych = *(YYMARKER = ++YYCURSOR);
    switch (yych)
      {
      case ':':
        goto yy14;
      default:
        goto yy3;
      }
  yy7:
    yych = *(YYMARKER = ++YYCURSOR);
    switch (yych)
      {
      case ':':
        goto yy15;
      default:
        goto yy3;
      }
  yy8:
    yych = *(YYMARKER = ++YYCURSOR);
    switch (yych)
      {
      case ':':
        goto yy16;
      default:
        goto yy3;
      }
  yy9:
    yych = *(YYMARKER = ++YYCURSOR);
    switch (yych)
      {
      case ':':
        goto yy17;
      default:
        goto yy3;
      }
  yy10:
    ++YYCURSOR;
#line 219 "php_serializer.re"
    {
      *p = YYCURSOR;
      return rval;
    }
#line 278 "php_serializer.c"
  yy12:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '+':
        goto yy18;
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy19;
      default:
        goto yy13;
      }
  yy13:
    YYCURSOR = YYMARKER;
    goto yy3;
  yy14:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '0':
      case '1':
        goto yy21;
      default:
        goto yy13;
      }
  yy15:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '+':
        goto yy22;
      case '-':
        goto yy23;
      case '.':
        goto yy24;
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy25;
      case 'I':
        goto yy27;
      case 'N':
        goto yy28;
      default:
        goto yy13;
      }
  yy16:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '+':
      case '-':
        goto yy29;
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy30;
      default:
        goto yy13;
      }
  yy17:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '+':
        goto yy32;
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy33;
      default:
        goto yy13;
      }
  yy18:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy19;
      default:
        goto yy13;
      }
  yy19:
    ++YYCURSOR;
    if ((YYLIMIT - YYCURSOR) < 2)
      YYFILL (2);
    yych = *YYCURSOR;
    switch (yych)
      {
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy19;
      case ':':
        goto yy35;
      default:
        goto yy13;
      }
  yy21:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case ';':
        goto yy36;
      default:
        goto yy13;
      }
  yy22:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '.':
        goto yy24;
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy25;
      default:
        goto yy13;
      }
  yy23:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '.':
        goto yy24;
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy25;
      case 'I':
        goto yy27;
      default:
        goto yy13;
      }
  yy24:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy38;
      default:
        goto yy13;
      }
  yy25:
    ++YYCURSOR;
    if ((YYLIMIT - YYCURSOR) < 4)
      YYFILL (4);
    yych = *YYCURSOR;
    switch (yych)
      {
      case '.':
        goto yy38;
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy25;
      case ';':
        goto yy40;
      case 'E':
      case 'e':
        goto yy42;
      default:
        goto yy13;
      }
  yy27:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case 'N':
        goto yy43;
      default:
        goto yy13;
      }
  yy28:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case 'A':
        goto yy44;
      default:
        goto yy13;
      }
  yy29:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy30;
      default:
        goto yy13;
      }
  yy30:
    ++YYCURSOR;
    if (YYLIMIT <= YYCURSOR)
      YYFILL (1);
    yych = *YYCURSOR;
    switch (yych)
      {
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy30;
      case ';':
        goto yy45;
      default:
        goto yy13;
      }
  yy32:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy33;
      default:
        goto yy13;
      }
  yy33:
    ++YYCURSOR;
    if ((YYLIMIT - YYCURSOR) < 2)
      YYFILL (2);
    yych = *YYCURSOR;
    switch (yych)
      {
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy33;
      case ':':
        goto yy47;
      default:
        goto yy13;
      }
  yy35:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '{':
        goto yy48;
      default:
        goto yy13;
      }
  yy36:
    ++YYCURSOR;
#line 224 "php_serializer.re"
    {
      *p = YYCURSOR;
      rval = parse_iv (start + 2) ? Qtrue : Qfalse;
      return rval;
    }
#line 558 "php_serializer.c"
  yy38:
    ++YYCURSOR;
    if ((YYLIMIT - YYCURSOR) < 4)
      YYFILL (4);
    yych = *YYCURSOR;
    switch (yych)
      {
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy38;
      case ';':
        goto yy40;
      case 'E':
      case 'e':
        goto yy42;
      default:
        goto yy13;
      }
  yy40:
    ++YYCURSOR;
#line 251 "php_serializer.re"
    {
      long str_len;
      VALUE rb_str;
      const char *str_p;

      *p = YYCURSOR;
      str_p = (const char *) start + 2;
      str_len = YYCURSOR - start - 3;
      rb_str = rb_str_new (str_p, str_len);
      rval = DBL2NUM (rb_str_to_dbl (rb_str, 0));
      return rval;
    }
#line 594 "php_serializer.c"
  yy42:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '+':
      case '-':
        goto yy50;
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy51;
      default:
        goto yy13;
      }
  yy43:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case 'F':
        goto yy53;
      default:
        goto yy13;
      }
  yy44:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case 'N':
        goto yy53;
      default:
        goto yy13;
      }
  yy45:
    ++YYCURSOR;
#line 230 "php_serializer.re"
    {
      *p = YYCURSOR;
      rval = LONG2FIX (parse_iv (start + 2));
      return rval;
    }
#line 632 "php_serializer.c"
  yy47:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '"':
        goto yy54;
      default:
        goto yy13;
      }
  yy48:
    ++YYCURSOR;
#line 291 "php_serializer.re"
    {
      VALUE hash = Qnil;
      VALUE array = Qnil;
      VALUE h_key = Qnil;
      VALUE h_val = Qnil;
      int is_array = 1;
      long elements;

      *p = YYCURSOR;

      elements = parse_iv (start + 2);
      hash = rb_hash_new ();
      array = rb_ary_new ();
      for (long i = 0; i < elements; i++)
        {
          h_key = unserialize_intern (p, max);
          h_val = unserialize_intern (p, max);
          rb_hash_aset (hash, h_key, h_val);
          if (TYPE (h_key) != T_FIXNUM || FIX2LONG (h_key) != i)
            is_array = 0;
          if (is_array)
            rb_ary_push (array, h_val);
        }
      *p += 1;
      rval = is_array ? array : hash;
      return rval;
    }
#line 669 "php_serializer.c"
  yy50:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '+':
      case '-':
        goto yy56;
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy51;
      default:
        goto yy13;
      }
  yy51:
    ++YYCURSOR;
    if (YYLIMIT <= YYCURSOR)
      YYFILL (1);
    yych = *YYCURSOR;
    switch (yych)
      {
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy51;
      case ';':
        goto yy40;
      default:
        goto yy13;
      }
  yy53:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case ';':
        goto yy57;
      default:
        goto yy13;
      }
  yy54:
    ++YYCURSOR;
#line 264 "php_serializer.re"
    {
      unsigned int len, maxlen;
      char *str;

      len = parse_uiv (start + 2);
      maxlen = max - YYCURSOR;
      if (maxlen < len)
        {
          raise_incomplete_serialization ();
        }

      str = (char *) YYCURSOR;
      YYCURSOR += len;

      if (*(YYCURSOR) != '"')
        {
          raise_incomplete_serialization ();
        }

      if (*(YYCURSOR + 1) != ';')
        {
          raise_incomplete_serialization ();
        }

      YYCURSOR += 2;
      *p = YYCURSOR;
      rval = rb_str_new (str, len);
      return rval;
    }
#line 740 "php_serializer.c"
  yy56:
    yych = *++YYCURSOR;
    switch (yych)
      {
      case '0':
      case '1':
      case '2':
      case '3':
      case '4':
      case '5':
      case '6':
      case '7':
      case '8':
      case '9':
        goto yy51;
      default:
        goto yy13;
      }
  yy57:
    ++YYCURSOR;
#line 236 "php_serializer.re"
    {
      const char *str;

      *p = YYCURSOR;
      str = (const char *) start + 2;
      if (!strncmp (str, "NAN", 3))
        {
          rval = rb_const_get (rb_cFloat, rb_intern ("NAN"));
        }
      else if (!strncmp (str, "INF", 3))
        {
          rval = rb_const_get (rb_cFloat, rb_intern ("INFINITY"));
        }
      else if (!strncmp (str, "-INF", 4))
        {
          rval =
            DBL2NUM (-RFLOAT_VALUE
                     (rb_const_get (rb_cFloat, rb_intern ("INFINITY"))));
        }
      return rval;
    }
#line 773 "php_serializer.c"
  }
#line 320 "php_serializer.re"


  return Qnil;
}

static VALUE
serialize (VALUE module, VALUE input)
{
  php_str buf = { 0 };
  VALUE serialized_data = Qnil;
  serialize_intern (&buf, input);
  serialized_data = rb_str_new (buf.c, buf.len);
  php_str_free (&buf);
  return serialized_data;
}

static VALUE
unserialize (VALUE module, VALUE input)
{
  unsigned char *str_p = (unsigned char *) RSTRING_PTR (input);
  long str_len = RSTRING_LEN (input);
  return unserialize_intern (&str_p, str_p + str_len);
}
